import * as THREE from 'three';

export const PlaneBufferGeometry    = THREE.PlaneGeometry;
export const CylinderBufferGeometry = THREE.CylinderGeometry;
export const sRGBEncoding           = THREE.sRGBEncoding;
export const LinearEncoding         = THREE.LinearEncoding;

export const AddEquation            = THREE.AddEquation;
export const AddOperation           = THREE.AddOperation;
export const AdditiveBlending       = THREE.AdditiveBlending;
export const AmbientLight           = THREE.AmbientLight;
export const AnimationClip          = THREE.AnimationClip;
export const AnimationMixer         = THREE.AnimationMixer;
export const AudioLoader            = THREE.AudioLoader;
export const AudioListener          = THREE.AudioListener;
export const BackSide               = THREE.BackSide;
export const Bone                   = THREE.Bone;
export const BooleanKeyframeTrack   = THREE.BooleanKeyframeTrack;
export const Box2                   = THREE.Box2;
export const Box3                   = THREE.Box3;
export const BufferAttribute        = THREE.BufferAttribute;
export const BufferGeometry         = THREE.BufferGeometry;
export const Camera                 = THREE.Camera;
export const Color                  = THREE.Color;
export const ColorKeyframeTrack     = THREE.ColorKeyframeTrack;
export const CylinderGeometry       = THREE.CylinderGeometry;
export const DoubleSide             = THREE.DoubleSide;
export const Euler                  = THREE.Euler;
export const Fog                    = THREE.Fog;
export const FrontSide              = THREE.FrontSide;
export const Group                  = THREE.Group;
export const InstancedBufferAttribute = THREE.InstancedBufferAttribute;
export const InstancedBufferGeometry  = THREE.InstancedBufferGeometry;
export const InstancedMesh          = THREE.InstancedMesh;
export const Light                  = THREE.Light;
export const LoadingManager         = THREE.LoadingManager;
export const Material               = THREE.Material;
export const Matrix3                = THREE.Matrix3;
export const Matrix4                = THREE.Matrix4;
export const Mesh                   = THREE.Mesh;
export const MeshBasicMaterial      = THREE.MeshBasicMaterial;
export const MeshLambertMaterial    = THREE.MeshLambertMaterial;
export const MeshPhongMaterial      = THREE.MeshPhongMaterial;
export const MeshStandardMaterial   = THREE.MeshStandardMaterial;
export const NearestFilter          = THREE.NearestFilter;
export const Object3D               = THREE.Object3D;
export const OrthographicCamera     = THREE.OrthographicCamera;
export const PerspectiveCamera      = THREE.PerspectiveCamera;
export const PlaneGeometry          = THREE.PlaneGeometry;
export const Quaternion             = THREE.Quaternion;
export const Raycaster              = THREE.Raycaster;
export const RepeatWrapping         = THREE.RepeatWrapping;
export const Renderer               = THREE.Renderer;
export const Scene                  = THREE.Scene;
export const ShaderMaterial         = THREE.ShaderMaterial;
export const Skeleton               = THREE.Skeleton;
export const Sphere                 = THREE.Sphere;
export const SpotLight              = THREE.SpotLight;
export const Texture                = THREE.Texture;
export const TextureLoader          = THREE.TextureLoader;
export const TriangleFanDrawMode   = THREE.TriangleFanDrawMode;
export const TriangleStripDrawMode = THREE.TriangleStripDrawMode;
export const TrianglesDrawMode     = THREE.TrianglesDrawMode;
export const UniformsUtils          = THREE.UniformsUtils;
export const Vector2                = THREE.Vector2;
export const Vector3                = THREE.Vector3;
export const Vector4                = THREE.Vector4;
export const VRButton               = THREE.VRButton;
export const WebGLRenderer          = THREE.WebGLRenderer;
export const WebGLRenderTarget      = THREE.WebGLRenderTarget;
export const Wrapping               = THREE.Wrapping;

export * from 'three';

// Default export THREE object
export default THREE;
